# Generated by Django 2.0.7 on 2018-07-25 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('releaseDate', models.DateTimeField()),
                ('genre', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=500)),
                ('geoRights', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
