# Generated by Django 2.0.7 on 2018-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True),
        ),
    ]
