# Generated by Django 2.0.7 on 2018-07-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='contentId',
        ),
    ]
