# Generated by Django 2.0.7 on 2018-07-28 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_content_contentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contentId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
