# Generated by Django 2.0.7 on 2018-07-28 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0006_content_contentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='contentId',
        ),
        migrations.AddField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
