# Generated by Django 2.0.7 on 2018-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180728_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True),
        ),
    ]
